### Вправа 1
Вводиться число n. Вивести масив розміру n×n, в
якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0.

In [1]:
# Варіант 1: Numpy
import numpy as np
import time

n = int(input("Введіть n: "))

start = time.time()
matrix_numpy = np.diag(np.arange(1, n+1))
end = time.time()

print(matrix_numpy)
print(f"Час виконання (NumPy): {end - start:.8f} сек")

Введіть n:  5


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
Час виконання (NumPy): 0.00030351 сек


In [23]:
#  Варіант 2: через цикли 
import time

n = int(input("Введіть n: "))

start = time.time()
matrix_loop = [[0]*n for _ in range(n)]
for i in range(n):
    matrix_loop[i][i] = i + 1
end = time.time()

for row in matrix_loop:
    print(row)
print(f"Час виконання (через цикли): {end - start:.8f} сек")

Введіть n:  5


[1, 0, 0, 0, 0]
[0, 2, 0, 0, 0]
[0, 0, 3, 0, 0]
[0, 0, 0, 4, 0]
[0, 0, 0, 0, 5]
Час виконання (через цикли): 0.00036621 сек


### Вправа 3
Вводяться 4 числа n, m, r, c. Вивести масив розміру
n×m, в якому в кожному рядку з номером r і в кожному стовпчику з
номером c стоять 0, а інші елементи дорівнюють 1.

In [24]:
# Варіант 1: Numpy
import numpy as np
import time

n, m, r, c = map(int, input("Введіть n, m, r, c: ").split())

start = time.time()
matrix_numpy = np.ones((n, m), dtype=int)
matrix_numpy[r] = 0
matrix_numpy[:, c] = 0
end = time.time()

print(matrix_numpy)
print(f"Час виконання (NumPy): {end - start:.8f} сек")


Введіть n, m, r, c:  6 7 2 3


[[1 1 1 0 1 1 1]
 [1 1 1 0 1 1 1]
 [0 0 0 0 0 0 0]
 [1 1 1 0 1 1 1]
 [1 1 1 0 1 1 1]
 [1 1 1 0 1 1 1]]
Час виконання (NumPy): 0.00043464 сек


In [20]:
# Варіант 2: через цикли
import time

n, m, r, c = map(int, input("Введіть n, m, r, c: ").split())

start = time.time()
matrix_loop = [[1]*m for _ in range(n)]

for i in range(n):
    for j in range(m):
        if i == r or j == c:
            matrix_loop[i][j] = 0
end = time.time()

for row in matrix_loop:
    print(row)
print(f"Час виконання (через цикли): {end - start:.8f} сек")


Введіть n, m, r, c:  4 7 1 2


[1, 1, 0, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 1, 1, 1, 1]
[1, 1, 0, 1, 1, 1, 1]
Час виконання (через цикли): 0.00047398 сек


### Вправа 4
Вводяться числа n і m. Вивести масив розміру n×m, в
якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0
до m–1, а всі інші елементи матриці дорівнюють 0.

In [25]:
#Варіант 1: Numpy
import numpy as np
import time

n, m = map(int, input("Введіть n і m: ").split())

start = time.time()
matrix_numpy = np.zeros((n, m), dtype=int)
matrix_numpy[0] = np.arange(m)
end = time.time()

print(matrix_numpy)
print(f"Час виконання (NumPy): {end - start:.8f} сек")

Введіть n і m:  3 4


[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]
Час виконання (NumPy): 0.00041461 сек


In [1]:
#Варіант 2: через цикли
import time

n, m = map(int, input("Введіть n і m: ").split())

start = time.time()
matrix_loop = [[0]*m for _ in range(n)]

for j in range(m):
    matrix_loop[0][j] = j
end = time.time()

for row in matrix_loop:
    print(row)
print(f"Час виконання (через цикли): {end - start:.8f} сек")

Введіть n і m:  3 4


[0, 1, 2, 3]
[0, 0, 0, 0]
[0, 0, 0, 0]
Час виконання (через цикли): 0.00046253 сек


### Вправа 6 
З клавіатури вводиться масив. Замінити всі ненульові
елементи на –1.

In [2]:
#Варіант 1: Numpy
import numpy as np
import time

arr = np.array([3, 4, 0, 9, 7, 0, 6, 0, 4, 0, 3])

start = time.time()
arr[arr != 0] = -1
end = time.time()

print(arr)
print(f"Час виконання (NumPy): {end - start:.8f} сек")



[-1 -1  0 -1 -1  0 -1  0 -1  0 -1]
Час виконання (NumPy): 0.00031304 сек


In [4]:
#Варіант 2: через цикли 
import time

arr = [3, 4, 0, 9, 7, 0, 6, 0, 4, 0, 3]

start = time.time()
for i in range(len(arr)):
    if arr[i] != 0:
        arr[i] = -1
end = time.time()

print(arr)
print(f"Час виконання (через цикли): {end - start:.8f} сек")


[-1, -1, 0, -1, -1, 0, -1, 0, -1, 0, -1]
Час виконання (через цикли): 0.00023103 сек
