### Вправа 10
Вводиться числа n i m. Створити масив випадкових
значень n×m і обчислити мінімальне, максимальне значення, середнє та
середньо квадратичне відхилення, округлене до 3 знаків після коми.

In [2]:
# Варіант 1: Numpy
import numpy as np
import time


n, m = map(int, input("Введіть n і m: ").split())

start = time.time()
matrix = np.random.random((n, m)) 

min_val = np.round(np.min(matrix), 3)
max_val = np.round(np.max(matrix), 3)
mean_val = np.round(np.mean(matrix), 3)
std_val = np.round(np.std(matrix), 3)
end = time.time()

print("\nМатриця випадкових чисел:")
print(matrix)
print(f"\nмінімум: {min_val}")
print(f"максимум: {max_val}")
print(f"середнє: {mean_val}")
print(f"середньоквадратичне відхилення: {std_val}")
print(f"Час виконання (NumPy): {end - start:.8f} сек")


Введіть n і m:  3 4



Матриця випадкових чисел:
[[0.55320265 0.8227762  0.90921444 0.26136906]
 [0.14041572 0.04981167 0.81243302 0.28437265]
 [0.7213784  0.09064659 0.90777441 0.31447516]]

мінімум: 0.05
максимум: 0.909
середнє: 0.489
середньоквадратичне відхилення: 0.319
Час виконання (NumPy): 0.00123477 сек


In [3]:
# Варіант 2: через цикли
import random
import math
import time

n, m = map(int, input("Введіть n і m: ").split())

start = time.time()
matrix = [[random.random() for _ in range(m)] for _ in range(n)]

values = [x for row in matrix for x in row]

min_val = round(min(values), 3)
max_val = round(max(values), 3)
mean_val = round(sum(values) / len(values), 3)
std_val = round(math.sqrt(sum((x - mean_val)**2 for x in values) / len(values)), 3)
end = time.time()

print("\nМатриця випадкових чисел:")
for row in matrix:
    print(row)

print(f"\nмінімум: {min_val}")
print(f"максимум: {max_val}")
print(f"середнє: {mean_val}")
print(f"середньоквадратичне відхилення: {std_val}")
print(f"Час виконання (через цикли): {end - start:.8f} сек")


Введіть n і m:  3 4



Матриця випадкових чисел:
[0.5478216313612396, 0.45389335003592224, 0.7077926734150822, 0.10806634684887662]
[0.8165490317496111, 0.5062051123878274, 0.6310118725795704, 0.8105913427221988]
[0.1494780484473487, 0.7081066887938061, 0.552002292521321, 0.6511668912989492]

мінімум: 0.108
максимум: 0.817
середнє: 0.554
середньоквадратичне відхилення: 0.218
Час виконання (через цикли): 0.00122762 сек


### Вправа 12
Створити масив одиниць розміром n×n та створити в
ньому «рамку», що утворюється з 0.

In [4]:
# Варіант 1: Numpy
import numpy as np
import time

n = int(input("Введіть n: "))

start = time.time()
matrix = np.ones((n, n))
matrix[0, :] = 0
matrix[-1, :] = 0
matrix[:, 0] = 0
matrix[:, -1] = 0
end = time.time()

print(matrix)
print(f"Час виконання (NumPy): {end - start:.8f} сек")


Введіть n:  4


[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]
Час виконання (NumPy): 0.00066853 сек


In [5]:
# Варіант 2: через цикли
import time

n = int(input("Введіть n: "))

start = time.time()
matrix = [[1]*n for _ in range(n)]

for i in range(n):
    for j in range(n):
        if i == 0 or i == n-1 or j == 0 or j == n-1:
            matrix[i][j] = 0
end = time.time()

for row in matrix:
    print(row)
print(f"Час виконання (через цикли): {end - start:.8f} сек")


Введіть n:  4


[0, 0, 0, 0]
[0, 1, 1, 0]
[0, 1, 1, 0]
[0, 0, 0, 0]
Час виконання (через цикли): 0.00047112 сек


### Вправа 15
Заповнити парні стовпчикі матриці розміром n×n
одиницями, а непарні – нулями.

In [6]:
# Варіант 1: Numpy
import numpy as np
import time

n = int(input("Введіть n: "))

start = time.time()
matrix = np.zeros((n, n), dtype=int)
matrix[:, 1::2] = 1  
end = time.time()

print(matrix)
print(f"Час виконання (NumPy): {end - start:.8f} сек")


Введіть n:  5


[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Час виконання (NumPy): 0.00038433 сек


In [7]:
# Варіант 2: через цикли
import time

n = int(input("Введіть n: "))

start = time.time()
matrix = [[0]*n for _ in range(n)]

for i in range(n):
    for j in range(n):
        if j % 2 != 0:  
            matrix[i][j] = 1
end = time.time()

for row in matrix:
    print(row)
print(f"Час виконання (через цикли): {end - start:.8f} сек")


Введіть n:  5


[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
[0, 1, 0, 1, 0]
Час виконання (через цикли): 0.00044751 сек


### Вправа 17
Заповнити вектор значеннями від 0 до n. Замінити
знаки для всіх значень, що менші за n/2 та більші за 3n/4 на
протилежні.

In [8]:
# Варіант 1: Numpy
import numpy as np
import time

n = int(input("Введіть n: "))

start = time.time()
vec = np.arange(0, n+1)
vec[(vec < n/2) | (vec > 3*n/4)] *= -1
end = time.time()

print(vec)
print(f"Час виконання (NumPy): {end - start:.8f} сек")


Введіть n:  6


[ 0 -1 -2  3  4 -5 -6]
Час виконання (NumPy): 0.00055742 сек


In [9]:
# Варіант 2: через цикли
import time

n = int(input("Введіть n: "))

start = time.time()
vec = list(range(n+1))

for i in range(len(vec)):
    if vec[i] < n/2 or vec[i] > 3*n/4:
        vec[i] *= -1
end = time.time()

print(vec)
print(f"Час виконання (через цикли): {end - start:.8f} сек")


Введіть n:  6


[0, -1, -2, 3, 4, -5, -6]
Час виконання (через цикли): 0.00042772 сек


### Вправа 18
Згенерувати вектор з n випадкових чисел в діапазоні
від 0 до 99. Визначити кількість унікальних чисел в послідовності.

In [1]:
# Варіант 1: Numpy
import numpy as np
import time

n = 10 

start = time.time()
vec = np.random.randint(0, 100, size=n) 
unique_count = len(np.unique(vec))
end = time.time()

print("Вектор:", vec)
print(f"Кількість унікальних елементів: {unique_count}")
print(f"Час виконання (NumPy): {end - start:.8f} сек")


Вектор: [73 29  0 59 34  0 86 38 81 40]
Кількість унікальних елементів: 9
Час виконання (NumPy): 0.01620054 сек


In [2]:
# Варіант 2: через цикли 
import random
import time

n = 10 

start = time.time()
vec = [random.randint(0, 99) for _ in range(n)]

unique_elements = []
for num in vec:
    if num not in unique_elements:
        unique_elements.append(num)

unique_count = len(unique_elements)
end = time.time()

print("Вектор:", vec)
print(f"Кількість унікальних елементів: {unique_count}")
print(f"Час виконання (через цикли): {end - start:.8f} сек")


Вектор: [37, 5, 4, 92, 74, 64, 96, 89, 40, 65]
Кількість унікальних елементів: 10
Час виконання (через цикли): 0.00056958 сек
