### Завдання 2
Розв’язати систему лінійних рівнянь формулами Крамера та перевірити розв’язок іншими методами:
- через матричне множення,
- через обернену матрицю,
- через функцію `numpy.linalg.solve()`,
- порівняти результати за допомогою `np.allclose()`.

In [3]:
# Метод Крамера
import numpy as np

A = np.array([
    [1, 5, 3, -4],
    [3, 1, -2, 0],
    [5, -7, 0, 10],
    [0, 3, -5, 0]
], dtype=float)

B = np.array([20, 9, -9, 1], dtype=float)

det_A = np.linalg.det(A)
X = np.zeros(4)

for i in range(4):
    Ai = A.copy()
    Ai[:, i] = B
    X[i] = np.linalg.det(Ai) / det_A

print("Розв'язок методом Крамера:")
print(X)

Розв'язок методом Крамера:
[ 3.  2.  1. -1.]


In [4]:
# Перевірка через матричне множення A·X
check = A.dot(X)
print("Перевірка A·X:")
print(check)

Перевірка A·X:
[20.  9. -9.  1.]


In [5]:
# Розв'язання через обернену матрицю
A_inv = np.linalg.inv(A)
X_inv = A_inv.dot(B)
print("Розв'язок через обернену матрицю:")
print(X_inv)

Розв'язок через обернену матрицю:
[ 3.  2.  1. -1.]


In [6]:
# Розв'язання через numpy.linalg.solve()
X_solve = np.linalg.solve(A, B)
print("Розв'язок через numpy.linalg.solve():")
print(X_solve)

Розв'язок через numpy.linalg.solve():
[ 3.  2.  1. -1.]


In [12]:
# Перевірка правильності результатів

print("A · X (повинно дорівнювати B):")
print(A.dot(X))          

print("\nПорівняння результатів між методами:")
print("Крамер = Обернена:", np.allclose(X, X_inv))
print("Крамер = solve():", np.allclose(X, X_solve))
print("Обернена = solve():", np.allclose(X_inv, X_solve))

A · X (повинно дорівнювати B):
[20.  9. -9.  1.]

Порівняння результатів між методами:
Крамер = Обернена: True
Крамер = solve(): True
Обернена = solve(): True


### Завдання 3. Обчислення матричного виразу

Розрахунок виконати двома способами:
- за допомогою бібліотеки **NumPy**;
- за допомогою звичайних **циклів** (без NumPy).

Після обчислення порівняти отримані результати та час виконання.


In [13]:
# Обчислення через NumPy
import numpy as np
import time

A = np.array([[5, 2, 0],
              [10, 4, 1],
              [7, 3, 2]], dtype=float)

B = np.array([[3, 6, -1],
              [-1, -2, 0],
              [2, 1, 3]], dtype=float)

start = time.time()
result_numpy = (A - B @ B) @ (2*A + B)
end = time.time()

print("Результат (NumPy):")
print(result_numpy)
print(f"Час (NumPy): {end - start:.8f} сек")

Результат (NumPy):
[[  91.   64.   32.]
 [ 257.  146.    1.]
 [-322. -135.  -51.]]
Час (NumPy): 0.01137686 сек


In [16]:
# Обчислення через звичайні цикли
import time

A = [[5, 2, 0],
     [10, 4, 1],
     [7, 3, 2]]

B = [[3, 6, -1],
     [-1, -2, 0],
     [2, 1, 3]]

start = time.time()

# 1) B * B
BB = [[0, 0, 0],
      [0, 0, 0],
      [0, 0, 0]]

for i in range(3):
    for j in range(3):
        s = 0
        for k in range(3):
            s += B[i][k] * B[k][j]
        BB[i][j] = s

# 2) A - BB
left = [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]

for i in range(3):
    for j in range(3):
        left[i][j] = A[i][j] - BB[i][j]

# 3) 2A + B
right = [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]

for i in range(3):
    for j in range(3):
        right[i][j] = 2 * A[i][j] + B[i][j]

# 4) (A - BB) * (2A + B)
result_loops = [[0, 0, 0],
                [0, 0, 0],
                [0, 0, 0]]

for i in range(3):
    for j in range(3):
        s = 0
        for k in range(3):
            s += left[i][k] * right[k][j]
        result_loops[i][j] = s

end = time.time()

print("Результат через цикли:")
for row in result_loops:
    print(row)

print("Час цикли:", end - start)


Результат через цикли:
[91, 64, 32]
[257, 146, 1]
[-322, -135, -51]
Час цикли: 0.001302957534790039


In [17]:
print("Чи однакові результати:", np.allclose(result_numpy, result_loops))

Чи однакові результати: True
